### ISSUE TITLE
Ported to Python 3

### ISSUE THREAD

**Issue by oleg-shilo** [viralogic/py-enumerable#1]
Hi there, 

_No I have no issue to report it's just GitHub offers no other way to contact a user but as to log an issue._

First of all I would like to express my great appreciation of you work on py_linq. I am a big admirer of LINQ and I was really glad when I discovered py_linq. 

I beleive you've done a great job and py_link deserves to be ported to Python 3. I took the liberty of forking the codebase and successfully completed this task. Please find my repository here: https://github.com/oleg-shilo/py-enumerable. Now I would like to contribute it back to the original project.

As I see the situation there can be a few scenarios for this:
- You can update py_linq with my changes via pull-request. Though in this case Python 2 users might be upset as the changes will definitely break the compatibility.
- You can make a dedicated Python 3 fork of py_linq. Though I am not sure how to manage two mutually exclusive packages in this case. 
- Judging from inactivity on this project it may happens that you have no further interest in continuing py_linq (sometimes it happens). In this case I can re-release it as a new package by myself with giving you the full credit for your work. But I consider this as rather plan B and prefer product to stay associated with its original creator. 

Please let me know what would be your preferred option.

Please do not hesitate to contact me via my CodePlex profile where you can contact me directly: https://www.codeplex.com/site/users/view/oleg_s

Thank you,
Oleg Shilo

**Comment by viralogic** [comment]
Hi Oleg!

Wow! Thank you so much. Your work is very much appreciated! Thank you for your kind words. I am happy you found it useful.

I will think about how I would like to proceed. My first thought is to do a PR and make the codebase Python 2 and 3 compatible, but I admit I only know 2 well. Never touched 3 very much, so don't know if this is even possible. Will have to read up on it. I am open to suggestions. If you are familiar with merging Python 3 into a Python 2 codebase without breaking,  we can share the repo and the credit for the library.

I looked at your code on the fork. You are correct about the last() method not needing to be sorted. Not sure what I was thinking there.

The project is still a little pet project of mine. Haven't forgotten about it, just haven't had much time to work on it. I branched from the master with grand plans to try and extend the library to an ORM similar to code first entity framework. Did some preliminary stuff to get it up and running on sqlite with no querying capability yet. Just creation of tables, inserts, deletes, and updates if I recall correctly.

Any way, let me know your thoughts on merging the two repos together. I am definitely willing to collaborate. I am just happy someone found it useful. I mostly just built it for my own purposes.

**Comment by oleg-shilo** [comment]
I am really glad the project isn't forgotten. 
In my case py2 vs py3 it's all the other way around. If I ever do Python then it's v3 and never v2. :) But even with Python3 I cannot say I am fluent in it. My all major achievements lays in C#/.NET area. 

In fact I am so interest in your product is because I found myself extremely disappointed with the absence of a nice consistent collection manipulation API that could be used in a Fluent manner from Python. To be honest ORM part of it has a much lower value for me (at least for now). 

`Any way, let me know your thoughts on merging the two repos together.`
I am afraid that my knowledge of the matter can be of a very limited help for this. But let me summarize the changes that I've done and may be this will help with the decision on how to proceed.

1. **Unit testing changes**
a. I had to remove ``__init__.py`` as it prevented running the test because of the changes how  Py3 treats this file. Quite possible there is a clever trick that allows avoiding the removal that I just don't know about. Though likely ``__init__.py`` will not cause any problems when the package is consumed via pip by user.
b. I also moved exceptions.py content to py_linq.py as it's path was shadowed with the current package folder structure.
 _
_Technically these changes only needed to allow development in Python3 but not necessarily to use the package. I've seen people not solving but avoiding these problems by simply having a flat file structure at the root. Not an elegant solution at all but may be an adequate one for simple packages. I hope that you you know some trick for this._ 

2. **Python 3 specific syntax and runtime behavior**
This includes changes for lambdas that no longer accept more than a single argument and work around for dicts not being sortable any more.
_
_These are the only real changes that need to be somehow done with care because they break v2 and without them v3 breaks too. Considering relatively low amount of these changes may be having a runtime condition (2 vs 3) checked and corresponding API invoked is good enough. 
This is where I am by far not an expert. In .NET I would just have two different implementations marked as v2-.. and v3-compatible and the NuGet package engine would import the one that is appropriate. Not sure what is the preferred pip approach in this case._

3. **py_linq.py specific changes**
Just a few minor adjustments to improve the code usability and support for a couple of new LINQ methods. 
_
_This is a simple one as most likely the all changes are fine for both versions of runtime._

I hope this helps. Take your time. Let me know when you are ready. I can create PR if you go this way. You can even port the changes one by one without engaging source control if it is more convenient. I just fond and tested the Py3 required changes but after that my role is rather to assist you. :)

**Comment by viralogic** [comment]
Hi Oleg,

Finally got around to adding code to py-linq to support Python 3. Wrote and tested code using 3.5.3. Nice thing is that all my previously written tests passed regardless of whether running tests in Python2 or Python3 so I would expect minimal breakage for users of previous versions...hopefully. Haven't pushed up the newest version with Python 3 support to PyPi yet (Version 0.4.0). Will expect to soon.

**Comment by oleg-shilo** [comment]
Fantastic. Txs. Please let me know when it is published.

**Comment by viralogic** [comment]
Now up on PyPi

pip install py-linq. Should autodetect Python 3 and import the appropriate Enumerable class. At least it did in my test in Python 3.5. Give it a whirl and please report any issues.

**Comment by oleg-shilo** [comment]
Great, thank you.
