### ISSUE TITLE
empty list as default parameter

### ISSUE THREAD

**Issue by scls19fr** [viralogic/py-enumerable#13]
Hello,

I read some times ago that passing empty list as default parameter is not a good practice.

so instead of

```
def myfunc(value=[]):
    pass
```
we should have

```
def myfunc(value=None):
    if value is None:
        value = []
```

This problem is exposed in
http://effbot.org/zone/default-values.htm
or
https://www.google.fr/search?q=python+empty+list+as+default+argument

Kind regards

**Comment by scls19fr** [comment]
Searching `=[]` into code helps but I prefer not to submit a PR for now as I would prefer to avoid git conflicts.

**Comment by viralogic** [comment]
Yeah, I can see how this isn't considered best practices. I think it is OK for constructors since you are allocating a new Enumerable object everytime a constructor is called, but I am fine with this small change. Will get to it soon.

**Comment by viralogic** [comment]
Fixed and committed code. Not sure when this will make it into PyPI at this point. I don't feel it is an urgent fix necessary for immediate release.
