### ISSUE TITLE
"Intersect"ing on the result of "distinct" yields incorrect results

### ISSUE THREAD

**Issue by boekabart** [viralogic/py-enumerable#19]
This passes:
```python
foo = Enumerable([1])
bar = Enumerable([1])
assert foo.intersect(bar).count() == 1
```
but when I add `.distinct()` to the `bar`:
```python
foo = Enumerable([1])
bar = Enumerable([1]).distinct()
assert foo.intersect(bar).count() == 1
```
it fails: `intersect.count` returns 0.

Fun fact: when 'enumerating' the `bar` before calling intersect, it works again...
```python
foo = Enumerable([1])
bar = Enumerable([1]).distinct()
fooBar = bar.count()
assert foo.intersect(bar).count() == 1
```

It seems Enumerable behaves more like a lazy<list>, by the way... after calling count() `print`ing the thing also changes from `<map...` to `[1]`

**Comment by viralogic** [comment]
Thanks very much. Will look into the issue and give you an update when I get a chance.

**Comment by viralogic** [comment]
@boekabart 
Released new version with this issue fixed. Version 0.7.0

pip install --upgrade py-linq
