### ISSUE TITLE
Handle predicate in more methods

### ISSUE THREAD

**Issue by K3UL** [viralogic/py-enumerable#21]
Hi, 

I too miss Linq, and I think this package would be a bigger consolation if it allowed predicates on the other methods than where(). I'm thinking most notably about First() and Last() (+ or default).

I don't think I need to explain further, but don't hesitate if you want me to precise something.

**Comment by viralogic** [comment]
@K3UL 
Thanks for your feedback. You make a valid point. Handling predicates on first and firstordefault is something that I missed.

https://docs.microsoft.com/en-us/dotnet/api/system.linq.enumerable.first?view=netframework-4.8#System_Linq_Enumerable_First__1_System_Collections_Generic_IEnumerable___0__System_Func___0_System_Boolean__

I will add this when I get a chance.

Thanks again.

**Comment by viralogic** [comment]
@K3UL 

Predicates for first, first_or_default, last, last_or_default are now supported. Version is 1.0.1. Thanks
