### ISSUE TITLE
"any" should not exhaust the entire iterator

### ISSUE THREAD

**Issue by dagoltz** [viralogic/py-enumerable#24]
See [MSDN](https://docs.microsoft.com/en-us/dotnet/api/system.linq.enumerable.any?view=netframework-4.7.2#System_Linq_Enumerable_Any__1_System_Collections_Generic_IEnumerable___0__):

> The enumeration of source is stopped as soon as the result can be determined.

It is also bad practice to exhaust the entire iterator just to see that it has at least 1 value.
The usage of "any" should use "first" or "element_at" to determine there is at least 1 element.

**Comment by viralogic** [comment]
merged into master
