### ISSUE TITLE
"reverse" should NOT be immediately executed

### ISSUE THREAD

**Issue by dagoltz** [viralogic/py-enumerable#31]
The current implementation uses "aggregate" which is an immediate executing function.
The "reverse" function should only keep state until the enumerable is iterated.

**Comment by viralogic** [comment]
hey @dagoltz ,

just wanted to say thank you for all the feedback. Appreciate it. Will get to it when I can.

**Comment by dagoltz** [comment]
@viralogic, I'll be happy to help solve some of those issues myself :)

**Comment by viralogic** [comment]
Sure. anytime you want to send me a PR, feel free.

**Comment by viralogic** [comment]
Merged into master
