### ISSUE TITLE
.first() unexcpected result

### ISSUE THREAD

**Issue by inielse** [viralogic/py-enumerable#35]
pip installed version 1.1.0 on Anaconda
I was doing a chain of x.where(..).order_by(..).first(), but kept getting an unexpected result
I can reproduce the behavior like this:

    from py_linq import Enumerable
    a = Enumerable([9,8,-7,6,5])
    b = a.order_by(lambda x: x)
    print(b.first())  #returns 9, was expecting -7
    print(list(b)[0]) #returns -7
    print(b.first())  #now it returns -7

**Comment by viralogic** [comment]
This fix will be a part of version 1.2
