### ISSUE TITLE
Enable continuous integration

### ISSUE THREAD

**Issue by scls19fr** [viralogic/py-enumerable#4]
A `.travis.yml`file is required at project root

```
language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"

# command to install dependencies
install:
  - "pip install -qq pytest"
  - "pip install -qq pytest-cov"
  - "pip install -qq flake8"
  - "pip install coveralls --quiet"
  - "pip install ."

# command to run tests
script:
  - py.test -s --cov=py_linq --cov-report xml:/tmp/cov-py_linq.xml --junitxml=/tmp/py_linq.xml
#  - flake8 --version
#  - flake8 --ignore E501 py_linq tests

after_success:
  - coveralls
```

and repository should be enabled on https://travis-ci.org/

**Comment by scls19fr** [comment]
flake8 is temporary disabled (because of #2)

**Comment by scls19fr** [comment]
Green build for Python 2.7 3.3 3.4 3.5 3.6
https://travis-ci.org/scls19fr/py-enumerable/builds/249188626

**Comment by viralogic** [comment]
CI changes have been merged and updated the CI badge. Thanks for the information and effort. Greatly appreciated.

**Comment by scls19fr** [comment]
You might remove `run_tests.py` as tests can be discovered and run automatically thanks to `test_...` naming an py.test usage.
keeping it can be misleading if you add some tests files (and forget to update `run_test.py` file)
