### ISSUE TITLE
Join does not behave the same as py-linq==1.2.1

### ISSUE THREAD

**Issue by ksusanto** [viralogic/py-enumerable#47]
from py_linq import Enumerable
marks = Enumerable([(25,'a'), (49,'b'), (50,'c'), (80,'d'), (90,'e')])
passing = marks.where(lambda x: x[0] >= 50) # results in [(50, 'c'), (80, 'd'), (90, 'e')]
omarks = Enumerable([(80,'eighty'),(49,'fortynine')])
omarks.join(passing, lambda o:o[0], lambda y:y[0], lambda result: result).to_list() 
# [((80, 'eighty'), (80, 'd'))]                                                 in py-linq==1.2.1
#[((80, 'eighty'), (80, 'd')), ((49, 'fortynine'), (49, 'b'))]          in py-linq==1.2.2

I think this is bug in 1.2.2, result supposed to be only  [((80, 'eighty'), (80, 'd'))]

**Comment by viralogic** [comment]
@ksusanto Thanks for the feedback. Will investigate as soon as I can.

**Comment by viralogic** [comment]
@ksusanto 
I was able to replicate your issue. A fix has been deployed. Version 1.2.3

`pip install --upgrade py-linq`
