### ISSUE TITLE
Consider add a method to_dict

### ISSUE THREAD

**Issue by norsd** [viralogic/py-enumerable#63]
How about add a method to_dict to Enumerable
like
to_dict(lambda x: x=>key, lambeda x: x=>value)

**Comment by viralogic** [comment]
@norsd 

Can you expand on what the inputs and outputs should be for this method? Is the result of this method a single dictionary, with the same number of keys as items in the collection? Are we just projecting a single property/field/key from each item in the collection? What are the lambda parameters for? Why do we need 2 lambda parameters?

Thanks,

Bruce
