### ISSUE TITLE
Consider adding some List extension equivalents

### ISSUE THREAD

**Issue by mzhukovs** [viralogic/py-enumerable#70]
While not technically in LINQ/on the Enumerable class in C#, this is Python so think these would be useful and fair game. For your consideration please (may try to contribute PR this weekend if time permits):

From List<T> extension methods:
[index_of](https://docs.microsoft.com/en-us/dotnet/api/system.collections.generic.list-1.indexof?view=net-5.0)
[last_index_of](https://docs.microsoft.com/en-us/dotnet/api/system.collections.generic.list-1.lastindexof?view=net-5.0)

And a potentially controversial but convenient one:
[for_each](https://docs.microsoft.com/en-us/dotnet/api/system.collections.generic.list-1.foreach?view=net-5.0)

Please let me know your thoughts @viralogic

**Comment by viralogic** [comment]
@mzhukovs 
Since we are currently working on a PR for this, I am going to close this issue.
